services:
  - type: web
    name: formapp
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    # O Procfile ser√° usado automaticamente
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: "app:app"
      - key: FLASK_ENV
        value: "production"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        fromDatabase:
          name: supabase
          property: connectionString
      - key: SUPABASE_KEY
        fromDatabase:
          name: supabase
          property: apiKey
    plan: free
    region: sao
