services:
  - type: web
    name: formapp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -c gunicorn_config.py app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: "app.py"
      - key: FLASK_ENV
        value: "production"
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        fromDatabase:
          name: supabase
          property: connectionString
      - key: SUPABASE_KEY
        fromDatabase:
          name: supabase
          property: apiKey
    plan: free
    region: sao
